INSERT INTO rooms (id, owner_id, name, host_name, min_user_num, max_user_num, use_cpu,status) VALUES
('018fce1a-fb22-71b1-9172-f86b3c7bb6c6', "Owner 1", 'Room 1', 'Host 1', 2, 10, TRUE, "finished"),
('018fce1b-03ba-718e-9137-f86b3c7bb6c7', "Owner 2", 'Room 2', 'Host 2', 3, 15, FALSE, "pending"),
('018fce1b-0ac3-71cb-bdcf-f86b3c7bb6c8', "Owner 3", 'Room 3', 'Host 3', 4, 20, TRUE, "playing"),
('018fce1b-12d2-718e-bb9e-f86b3c7bb6c9', "Owner 4", 'Room 4', 'Host 4', 5, 25, FALSE, "playing"),
('018fce1b-1ad1-71ab-8a21-f86b3c7bb6ca', "Owner 5", 'Room 5', 'Host 5', 1, 5, TRUE, "matched"),
('018fce1b-22f0-71cd-9017-f86b3c7bb6cb', "Owner 6", 'Room 6', 'Host 6', 2, 10, FALSE, "pending"),
('018fce1b-2b32-7198-8824-f86b3c7bb6cc', "Owner 7", 'Room 7', 'Host 7', 3, 15, TRUE, "finished"),
('018fce1b-32e3-71be-8e31-f86b3c7bb6cd', "Owner 8", 'Room 8', 'Host 8', 4, 20, FALSE,"matched"),
('018fce1b-3a13-71e4-bbf7-f86b3c7bb6ce', "Owner 9", 'Room 9', 'Host 9', 5, 25, TRUE,"finished"),
('018fce1b-4262-71a1-891d-f86b3c7bb6cf', "Owner 10", 'Room 10', 'Host 10', 1, 5, FALSE, "playing");

INSERT INTO problems (collect_sentence, level) VALUES
-- Level 1 (1-4文字)
('go', 1), ('api', 1), ('aws', 1), ('bash', 1), ('bit', 1),
('cli', 1), ('css', 1), ('db', 1), ('go', 1), ('git', 1),
('gui', 1), ('gcp', 1), ('gin', 1), ('html', 1), ('java', 1),
('js', 1), ('kubectl', 1), ('k8s', 1), ('zsh', 1), ('npm', 1),
('json', 1), ('yaml', 1), ('nano', 1), ('node', 1), ('php', 1),
('pip', 1), ('sql', 1), ('tdd', 1), ('vim', 1), ('vue', 1),
('xml', 1), ('yarn', 1), ('zshrc', 1), ('rest', 1), ('zsh', 1),
('ux', 1), ('ui', 1), ('csv', 1), ('orm', 1), ('mvc', 1),
('c++', 1), ('c#', 1), ('fp', 1), ('oop', 1), ('nosql', 1),
('ws', 1), ('rpc', 1), ('jsx', 1), ('ts', 1), ('py', 1),

-- Level 2 (5-8文字)
('python', 2), ('docker', 2), ('express', 2), ('gitlab', 2),
('bitbucket', 2), ('terraform', 2), ('flask', 2), ('java', 2),
('node.js', 2), ('next.js', 2), ('fastapi', 2), ('nuxt', 2),
('go', 2), ('pipecd', 2), ('mysql', 2), ('echo', 2),
('hackz', 2), ('react', 2), ('rails', 2), ('r', 2),
('kafka', 2), ('svelte', 2), ('angular', 2), ('vue', 2),
('jest', 2), ('redux', 2), ('jinja', 2), ('lambda', 2),
('jenkins', 2), ('typescript', 2), ('typescript', 2),
('redis', 2), ('sqlite', 2), ('mocha', 2), ('chai', 2),
('kustomize', 2), ('spring', 2), ('bitbucket', 2), ('next', 2),
('redux', 2), ('bashrc', 2), ('restapi', 2), ('bitbucket', 2),
('jenkins', 2), ('typescript', 2), ('typescript', 2),
('typescript', 2), ('typescript', 2),

-- Level 3 (9-12文字)
('docker-compose', 3), ('javascript', 3), ('typescript', 3),
('postgresql', 3), ('kubernetes', 3), ('jenkinsci', 3),
('bitbucketci', 3), ('kibana', 3), ('elasticsearch', 3),
('algolia', 3), ('travisci', 3), ('expressjs', 3),
('serverless', 3), ('django', 3), ('cloudrun', 3),
('firestore', 3), ('appengine', 3), ('lambda', 3),
('cloudformation', 3), ('terraformplan', 3),
('terraformapply', 3), ('sentry', 3), ('nodejs', 3),
('firebase', 3), ('junit', 3), ('kotlin', 3),
('typescript', 3), ('expressjs', 3), ('mongodb', 3),
('nuxtjs', 3), ('typescript', 3), ('springboot', 3),
('docker-compose', 3), ('typescript', 3), ('jenkinsfile', 3),
('typescript', 3), ('bitbucketci', 3), ('k8s', 3),
('sentry', 3), ('kafka', 3), ('typescript', 3),
('sentry', 3), ('typescript', 3), ('typescript', 3),
('jenkinsfile', 3), ('jenkinsfile', 3), ('jenkinsfile', 3),
('jenkinsfile', 3), ('jenkinsfile', 3), ('jenkinsfile', 3),

-- Level 4 (13-16文字)
('continuous integration', 4), ('cloud computing', 4),
('microservices architecture', 4), ('serverless functions', 4),
('virtual machines', 4), ('infrastructure as code', 4),
('scalable applications', 4), ('load balancer', 4),
('firewall settings', 4), ('ssl certificates', 4),
('distributed systems', 4), ('data encryption', 4),
('network protocols', 4), ('version control systems', 4),
('application programming interface', 4), ('database management systems', 4),
('web development frameworks', 4), ('container orchestration', 4),
('automated testing', 4), ('deployment pipelines', 4),
('real-time analytics', 4), ('data lakes', 4),
('data warehouses', 4), ('etl processes', 4),
('data governance', 4), ('data lineage', 4),
('master data management', 4), ('data quality', 4),
('data integration', 4), ('data federation', 4),
('event-driven architecture', 4), ('command query responsibility segregation', 4),
('event sourcing', 4), ('domain-driven design', 4),
('bounded contexts', 4), ('micro-frontends', 4),
('progressive web apps', 4), ('server-side rendering', 4),
('client-side rendering', 4), ('static site generation', 4),
('jamstack', 4), ('headless cms', 4),
('content delivery networks', 4), ('edge computing', 4),
('fog computing', 4), ('mesh networks', 4),
('peer-to-peer networks', 4), ('content distribution', 4),
('network latency', 4), ('network throughput', 4),

-- Level 5 (17-20文字)
('machine learning algorithms', 5), ('deep learning frameworks', 5),
('natural language processing', 5), ('artificial intelligence', 5),
('big data analytics', 5), ('data warehousing', 5),
('predictive analytics', 5), ('business intelligence', 5),
('data visualization tools', 5), ('data governance', 5),
('reinforcement learning', 5), ('supervised learning', 5),
('unsupervised learning', 5), ('semi-supervised learning', 5),
('self-supervised learning', 5), ('transfer learning', 5),
('few-shot learning', 5), ('zero-shot learning', 5),
('meta-learning', 5), ('automated machine learning', 5),
('hyperparameter tuning', 5), ('model selection', 5),
('model evaluation', 5), ('model interpretability', 5),
('model explainability', 5), ('feature engineering', 5),
('feature selection', 5), ('feature extraction', 5),
('dimensionality reduction', 5), ('principal component analysis', 5),
('singular value decomposition', 5), ('t-SNE', 5),
('umap', 5), ('clustering algorithms', 5),
('k-means clustering', 5), ('hierarchical clustering', 5),
('dbscan', 5), ('gmm', 5),
('ensemble methods', 5), ('random forests', 5),
('gradient boosting', 5), ('xgboost', 5),
('lightgbm', 5), ('catboost', 5),
('neural networks', 5), ('convolutional neural networks', 5),
('recurrent neural networks', 5), ('transformer models', 5),
('graph neural networks', 5),
('variational autoencoders', 5), ('sequence-to-sequence models', 5),

-- Level 6 (21-24文字)
('asynchronous programming', 6), ('real-time data processing', 6),
('high availability systems', 6), ('cloud-native applications', 6),
('multi-tenant architecture', 6), ('database replication', 6),
('horizontal scaling', 6), ('vertical scaling', 6),
('cloud storage solutions', 6), ('object storage', 6),
('block storage', 6), ('file storage', 6),
('content-addressable storage', 6), ('distributed file systems', 6),
('data sharding', 6), ('data partitioning', 6),
('consistent hashing', 6), ('eventual consistency', 6),
('strong consistency', 6), ('distributed transactions', 6),
('two-phase commit', 6), ('three-phase commit', 6),
('cap theorem', 6), ('base properties', 6),
('acid properties', 6), ('global transactions', 6),
('cross-region replication', 6), ('multi-master replication', 6),
('conflict resolution', 6), ('data versioning', 6),
('time-series databases', 6), ('graph databases', 6),
('document databases', 6), ('key-value stores', 6),
('wide-column stores', 6), ('in-memory databases', 6),
('search engines', 6), ('indexing strategies', 6),
('full-text search', 6), ('information retrieval', 6),
('semantic search', 6), ('fuzzy search', 6),
('query optimization', 6), ('query planning', 6),
('execution plans', 6), ('query execution', 6),
('data locality', 6), ('data compression', 6),
('data deduplication', 6), ('data archiving', 6),
('data retention policies', 6),

-- Level 7 (25-28文字)
('software development lifecycle', 7), ('agile methodologies', 7),
('scrum framework', 7), ('kanban system', 7),
('devops practices', 7), ('site reliability engineering', 7),
('continuous delivery', 7), ('monitoring and observability', 7),
('incident management', 7), ('root cause analysis', 7),
('value stream mapping', 7), ('lean principles', 7),
('extreme programming', 7), ('test-driven development', 7),
('behavior-driven development', 7), ('acceptance test-driven development', 7),
('pair programming', 7), ('mob programming', 7),
('code reviews', 7), ('code refactoring', 7),
('technical debt management', 7), ('legacy code migration', 7),
('feature toggles', 7), ('continuous refactoring', 7),
('incremental delivery', 7), ('iterative development', 7),
('minimum viable product', 7), ('customer feedback loops', 7),
('user story mapping', 7), ('impact mapping', 7),
('story splitting', 7), ('estimation techniques', 7),
('planning poker', 7), ('t-shirt sizing', 7),
('relative sizing', 7), ('velocity tracking', 7),
('burn down charts', 7), ('burn up charts', 7),
('cumulative flow diagrams', 7), ('lead time', 7),
('cycle time', 7), ('throughput', 7),
('bottleneck analysis', 7), ('workflow automation', 7),
('chatops', 7), ('infrastructure as code', 7),
('configuration management', 7), ('immutable infrastructure', 7),
('service level objectives', 7), ('service level agreements', 7),
('error budgets', 7), ('blameless postmortems', 7),
('game days', 7), ('chaos engineering', 7),

-- Level 8 (29-32文字)
('cloud-native security', 8), ('zero trust architecture', 8),
('identity and access management', 8), ('network security', 8),
('application security', 8), ('data security', 8),
('encryption algorithms', 8), ('public key infrastructure', 8),
('certificate authorities', 8), ('security protocols', 8),
('secure socket layer', 8), ('transport layer security', 8),
('multi-factor authentication', 8), ('single sign-on', 8),
('security information and event management', 8),
('intrusion detection systems', 8), ('intrusion prevention systems', 8),
('firewall configurations', 8), ('network segmentation', 8),
('virtual private networks', 8), ('secure web gateways', 8),
('cloud access security brokers', 8), ('endpoint security', 8),
('data loss prevention', 8), ('security incident response', 8),
('security orchestration automation and response', 8),
('vulnerability management', 8), ('penetration testing', 8),
('red teaming', 8), ('blue teaming', 8),
('purple teaming', 8), ('security awareness training', 8),
('security compliance frameworks', 8), ('regulatory requirements', 8),
('privacy laws', 8), ('data protection regulations', 8),
('industry standards', 8), ('security best practices', 8),
('secure coding guidelines', 8), ('security testing methodologies', 8),
('threat modeling', 8), ('risk assessment', 8),
('incident response planning', 8), ('business continuity planning', 8),
('disaster recovery planning', 8), ('crisis management', 8),
('security governance', 8), ('risk management', 8),
('compliance management', 8), ('security operations', 8),
('security architecture', 8), ('security engineering', 8),
('security analytics', 8), ('security monitoring', 8),

-- Level 9 (33-36文字)
('container orchestration and management systems', 9),
('continuous delivery and continuous deployment', 9),
('high availability and disaster recovery strategies', 9),
('machine learning model training and deployment', 9),
('real-time data processing and analytics systems', 9),
('infrastructure as code and configuration management', 9),
('serverless computing and event-driven architecture', 9),
('cloud-native application development and deployment', 9),
('distributed ledger technologies and blockchain', 9),
('multi-cloud strategy and hybrid cloud environments', 9),
('network security and threat detection systems', 9),
('automated software testing and quality assurance', 9),
('containerization and container orchestration tools', 9),
('application performance monitoring and logging', 9),
('service mesh architecture and microservices', 9),
('infrastructure monitoring and alerting systems', 9),
('data warehousing and big data analytics', 9),
('distributed systems and fault tolerance', 9),
('continuous integration and delivery pipelines', 9),
('cloud infrastructure management and automation', 9),
('high-performance computing and parallel processing', 9),
('edge computing and IoT infrastructure', 9),
('data privacy and regulatory compliance', 9),
('serverless architecture and function as a service', 9),
('network segmentation and security zoning', 9),
('identity and access management solutions', 9),
('data visualization and reporting tools', 9),
('server-side rendering and client-side rendering', 9),
('database replication and high availability', 9),
('artificial intelligence and machine learning', 9),
('cloud-native security and compliance', 9),
('data lakes and data warehousing solutions', 9),
('continuous security and vulnerability management', 9),
('event-driven architecture and microservices', 9),
('real-time data streaming and processing', 9),
('container orchestration and management tools', 9),
('network protocols and data communication', 9),
('automated deployment and infrastructure as code', 9),
('distributed ledger and blockchain technologies', 9),
('cloud-native application development tools', 9),
('infrastructure automation and orchestration', 9),
('high availability and fault tolerance', 9),
('real-time analytics and data processing', 9),
('continuous delivery and deployment pipelines', 9),
('cloud infrastructure and automation tools', 9),
('distributed systems and microservices architecture', 9),
('serverless computing and cloud-native applications', 9),
('cloud-native security and compliance tools', 9),
('machine learning and artificial intelligence', 9),
('network security and threat detection', 9),

-- Level 10 (33-50文字)
('func main() {fmt.Println("Hello, World")}', 10),
('int main() {printf("Hello, World\n"); return 0}', 10),
('CREATE TABLE hello_world (message VARCHAR(255))', 10),
('SELECT "Hello, World" FROM hello_world;', 10),
('print("Hello, World")', 10),
('System.out.println("Hello, World")', 10),
('console.log("Hello, World")', 10),
('echo "Hello, World"', 10),
('puts "Hello, World"', 10),
('alert("Hello, World")', 10),
('document.write("Hello, World")', 10),
('document.getElementById("demo").innerHTML = "Hello, World";', 10),
('high availability, disaster recovery, and fault tolerance', 10),
('infrastructure as code, configuration management, and automation', 10),
('real-time data processing, streaming, and analytics systems', 10),
('continuous integration, delivery, and deployment pipelines', 10),
('machine learning model training, deployment, and monitoring', 10),
('container orchestration, management, and scaling tools', 10),
('serverless computing, function as a service, and event-driven architecture', 10),
('cloud-native application development, deployment, and scaling', 10),
('distributed ledger technologies, blockchain, and cryptocurrency', 10),
('multi-cloud strategy, hybrid cloud environments, and cloud management', 10),
('network security, threat detection, and incident response', 10),
('automated software testing, quality assurance, and CI/CD', 10),
('application performance monitoring, logging, and observability', 10),
('service mesh architecture, microservices, and API gateways', 10),
('data warehousing, big data analytics, and data lakes', 10),
('distributed systems, fault tolerance, and scalability', 10),
('cloud infrastructure management, monitoring, and automation', 10),
('high-performance computing, parallel processing, and grid computing', 10),
('edge computing, IoT infrastructure, and real-time data', 10),
('data privacy, regulatory compliance, and data governance', 10),
('server-side rendering, client-side rendering, and SSR/CSR', 10),
('database replication, high availability, and disaster recovery', 10),
('artificial intelligence, machine learning, and deep learning', 10),
('cloud-native security, compliance, and threat management', 10),
('continuous security, vulnerability management, and DevSecOps', 10),
('event-driven architecture, microservices, and serverless functions', 10),
('real-time data streaming, processing, and analytics', 10),
('container orchestration, management, and monitoring tools', 10),
('network protocols, data communication, and security', 10),
('automated deployment, infrastructure as code, and CI/CD', 10),
('distributed ledger, blockchain technologies, and DLTs', 10),
('cloud-native application development, tools, and practices', 10),
('infrastructure automation, orchestration, and management', 10),
('high availability, fault tolerance, and disaster recovery', 10),
('real-time analytics, data processing, and visualization', 10),
('continuous delivery, deployment pipelines, and automation', 10),
('cloud infrastructure, automation tools, and monitoring', 10),
('distributed systems, microservices, and architecture', 10),
('serverless computing, cloud-native applications, and FaaS', 10),
('cloud-native security, compliance, and monitoring tools', 10),
('machine learning, artificial intelligence, and data science', 10),
('network security, threat detection, and prevention', 10);
