INSERT INTO rooms (id, owner_id, name, host_name, min_user_num, max_user_num, use_cpu,status) VALUES
('018fce1a-fb22-71b1-9172-f86b3c7bb6c6', "Owner 1", 'Room 1', 'Host 1', 2, 10, TRUE, "finished"),
('018fce1b-03ba-718e-9137-f86b3c7bb6c7', "Owner 2", 'Room 2', 'Host 2', 3, 15, FALSE, "pending"),
('018fce1b-0ac3-71cb-bdcf-f86b3c7bb6c8', "Owner 3", 'Room 3', 'Host 3', 4, 20, TRUE, "playing"),
('018fce1b-12d2-718e-bb9e-f86b3c7bb6c9', "Owner 4", 'Room 4', 'Host 4', 5, 25, FALSE, "playing"),
('018fce1b-1ad1-71ab-8a21-f86b3c7bb6ca', "Owner 5", 'Room 5', 'Host 5', 1, 5, TRUE, "matched"),
('018fce1b-22f0-71cd-9017-f86b3c7bb6cb', "Owner 6", 'Room 6', 'Host 6', 2, 10, FALSE, "pending"),
('018fce1b-2b32-7198-8824-f86b3c7bb6cc', "Owner 7", 'Room 7', 'Host 7', 3, 15, TRUE, "finished"),
('018fce1b-32e3-71be-8e31-f86b3c7bb6cd', "Owner 8", 'Room 8', 'Host 8', 4, 20, FALSE,"matched"),
('018fce1b-3a13-71e4-bbf7-f86b3c7bb6ce', "Owner 9", 'Room 9', 'Host 9', 5, 25, TRUE,"finished"),
('018fce1b-4262-71a1-891d-f86b3c7bb6cf', "Owner 10", 'Room 10', 'Host 10', 1, 5, FALSE, "playing");

INSERT INTO problems (collect_sentence, level) VALUES
-- Level 1
('go', 1),
('hackz', 1),
('echo', 1),
('docker', 1),
('react', 1),
('gin', 1),
('python', 1),
('java', 1),
('ruby', 1),
('php', 1),

-- Level 2
('pipecd', 2),
('mysql', 2),
('next.js', 2),
('websocket', 2),
('RedBull', 2),
('javascript', 2),
('typescript', 2),
('node.js', 2),
('express', 2),
('mongodb', 2),

-- Level 3
('postgresql', 3),
('kubernetes', 3),
('terraform', 3),
('ansible', 3),
('jenkins', 3),
('gitlab', 3),
('github', 3),
('bitbucket', 3),
('circleci', 3),
('docker-compose', 3),

-- Level 4
('cloud computing', 4),
('continuous integration', 4),
('microservices architecture', 4),
('serverless functions', 4),
('virtual machines', 4),
('infrastructure as code', 4),
('scalable applications', 4),
('load balancer', 4),
('firewall settings', 4),
('SSL certificates', 4),
('sudo rm -rf /', 4),

-- Level 5
('distributed systems', 5),
('data encryption', 5),
('network protocols', 5),
('version control systems', 5),
('application programming interface', 5),
('database management systems', 5),
('web development frameworks', 5),
('container orchestration', 5),
('automated testing', 5),
('deployment pipelines', 5),

-- Level 6
('asynchronous programming', 6),
('event-driven architecture', 6),
('real-time data processing', 6),
('high availability systems', 6),
('cloud-native applications', 6),
('multi-tenant architecture', 6),
('database replication', 6),
('horizontal scaling', 6),
('vertical scaling', 6),
('cloud storage solutions', 6),

-- Level 7
('machine learning algorithms', 7),
('deep learning frameworks', 7),
('natural language processing', 7),
('artificial intelligence', 7),
('big data analytics', 7),
('data warehousing', 7),
('predictive analytics', 7),
('business intelligence', 7),
('data visualization tools', 7),
('data governance', 7),

-- Level 8
('software development lifecycle', 8),
('agile methodologies', 8),
('scrum framework', 8),
('kanban system', 8),
('devops practices', 8),
('site reliability engineering', 8),
('continuous delivery', 8),
('monitoring and observability', 8),
('incident management', 8),
('root cause analysis', 8),

-- Level 9
('blockchain technology', 9),
('smart contracts', 9),
('cryptocurrency', 9),
('distributed ledger technology', 9),
('decentralized applications', 9),
('peer-to-peer networks', 9),
('cryptographic algorithms', 9),
('secure coding practices', 9),
('penetration testing', 9),
('ethical hacking', 9),
('git push -f origin main', 9),
('git commit --allow-empty', 9),

-- Level 10
('func main() {fmt.Println("Hello, World")}', 10),
('int main() {printf("Hello, World\n"); return 0}', 10),
('CREATE TABLE hello_world (message VARCHAR(255))', 10),
('SELECT "Hello, World" FROM hello_world;', 10),
('print("Hello, World")', 10),
('System.out.println("Hello, World")', 10),
('console.log("Hello, World")', 10);