apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timer
  template:
    metadata:
      labels:
        app: timer
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
        - name: timer
          image: asia-northeast1-docker.pkg.dev/stego-426014/stego-docker-prd/timer:276f88326ed7c42f6518f5909589a4b46960d8c9
          ports:
            - containerPort: 50000
              protocol: TCP
