apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timer
  template:
    metadata:
      labels:
        app: timer
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
        - name: timer
          image: asia-northeast1-docker.pkg.dev/stego-426014/stego-docker-prd/timer:0f3f4617d84e5efc237af0997272b6105ddc918f
          ports:
            - containerPort: 50000
              protocol: TCP
