apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timer
  template:
    metadata:
      labels:
        app: timer
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
        - name: timer
          image: asia-northeast1-docker.pkg.dev/stego-426014/stego-docker-prd/timer:b6ac8aa9474fb77a0af2af10f701543c85c3ac90
          ports:
            - containerPort: 50000
              protocol: TCP
