apiVersion: v1
kind: Service
metadata:
  name: timer-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: timer
  ports:
    - port: 50000
      targetPort: 50000
      protocol: TCP