apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: asia-northeast1-docker.pkg.dev/stego-426014/stego-docker-prd/web:d65f4d9cd3d9aee53fc7b2b5badb2615a6b15428
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_PROD_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gke-web-firebase-secrets
                  key: auth-api-key
            - name: NEXT_PUBLIC_DEV_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: gke-web-firebase-secrets
                  key: auth-domain
            - name: NEXT_PUBLIC_PROD_API_BASE_URL
              value: "https://api.ottotto.dev"
            - name: NEXT_PUBLIC_PROD_WS_BASE_URL
              value: "wss://api.ottotto.dev"
