apiVersion: "pipecd.dev/v1beta1"
kind: ControlPlane
spec:
  stateKey: pipecd-state
  datastore:
    type: FIRESTORE
    config:
      namespace: pipecd
      environment: prd
      project: stego-426014
      collectionNamePrefix: stego-pipecd
      # Must be a service account with "Cloud Datastore User" and "Cloud Datastore Index Admin" roles
      # since PipeCD needs them to creates the needed Firestore composite indexes in the background.
      credentialsFile: /etc/pipecd-secret/firestore-service-account
  filestore:
    type: GCS
    config:
      bucket: stego-pipecd
      # Must be a service account with "Storage Object Admin (roles/storage.objectAdmin)" role on the given bucket
      # since PipeCD need to write file object such as deployment log file to that bucket.
      credentialsFile: /etc/pipecd-secret/gcs-service-account